INSERT INTO JOB_CATEGORY(NAME) VALUES ('kategorija1')
INSERT INTO JOB_CATEGORY(NAME) VALUES ('kategorija2')
INSERT INTO JOB_CATEGORY(NAME) VALUES ('kategorija3')

INSERT INTO USER(ADDRESS, CITY, DISTANCE, EMAIL, LATITUDE, LONGITUDE, NAME, PASSWORD, POST_NUMBER, RANDOM_KEY, REGISTRATED, ROLE, USER_NAME,NUMBER_OF_MARKS,SUM_OF_MARKS) VALUES ('Karadjordjeva', 'Novi Sad', 0.0, 'olja.miljatovic@yahoo.com', 44.3868886, 19.103209, 'Olja', 'oljaolja', '15320','EAW6JNQ8IR0J4822HW', 1, 1, 'olja',0,0)
INSERT INTO USER(ADDRESS,  CITY, DISTANCE, EMAIL, LATITUDE, LONGITUDE, NAME, PASSWORD, POST_NUMBER, RANDOM_KEY, REGISTRATED, ROLE, USER_NAME,NUMBER_OF_MARKS,SUM_OF_MARKS ) VALUES ('Karadjordjeva', 'Novi Sad', 150, 'oljicamiljatovic@gmai.com', 45.2671352, 19.8335496, 'vlado', 'vlado', '15320','WWW6JNQ8IR0J3422HO', 1, 2, 'vlado',0,0)
INSERT INTO USER(ADDRESS,  CITY, DISTANCE, EMAIL, LATITUDE, LONGITUDE, NAME, PASSWORD, POST_NUMBER, RANDOM_KEY, REGISTRATED, ROLE, USER_NAME ,NUMBER_OF_MARKS,SUM_OF_MARKS) VALUES ('Karadjordjeva', 'Novi Sad', 170, 'oljicamiljatovic@gmai.com', 45.2671352, 19.8335496, 'danilo', 'danilo', '15320','WWW6JNQ8IR0J3422HO', 1, 2, 'danilo',0,0)
INSERT INTO USER(ADDRESS,  CITY, DISTANCE, EMAIL, LATITUDE, LONGITUDE, NAME, PASSWORD, POST_NUMBER, RANDOM_KEY, REGISTRATED, ROLE, USER_NAME,NUMBER_OF_MARKS,SUM_OF_MARKS ) VALUES ('Karadjordjeva', 'Novi Sad', 140, 'oljicamiljatovic@gmai.com', 45.2671352, 19.8335496, 'sanja', 'sanja', '15320','WWW6JNQ8IR0J3422HO', 1, 2, 'sanja',0,0)
INSERT INTO USER(ADDRESS,  CITY, DISTANCE, EMAIL, LATITUDE, LONGITUDE, NAME, PASSWORD, POST_NUMBER, RANDOM_KEY, REGISTRATED, ROLE, USER_NAME,NUMBER_OF_MARKS,SUM_OF_MARKS ) VALUES ('Karadjordjeva', 'Novi Sad', 160, 'oljicamiljatovic@gmai.com', 45.2671352, 19.8335496, 'miki', 'miki', '15320','WWW6JNQ8IR0J3422HO', 1, 2, 'miki',0,0)
INSERT INTO USER(ADDRESS,  CITY, DISTANCE, EMAIL, LATITUDE, LONGITUDE, NAME, PASSWORD, POST_NUMBER, RANDOM_KEY, REGISTRATED, ROLE, USER_NAME ,NUMBER_OF_MARKS,SUM_OF_MARKS) VALUES ('Karadjordjeva', 'Novi Sad', 160, 'oljicamiljatovic@gmai.com', 45.2671352, 19.8335496, 'sake', 'sake', '15320','WWW6JNQ8IR0J3422HO', 1, 2, 'sake',0,0)


INSERT INTO USER(ADDRESS,  CITY, DISTANCE, EMAIL, LATITUDE, LONGITUDE, NAME, PASSWORD, POST_NUMBER, RANDOM_KEY, REGISTRATED, ROLE, USER_NAME,NUMBER_OF_MARKS,SUM_OF_MARKS ) VALUES ('Karadjordjeva', 'Novi Sad', 160, 'oljicamiljatovic@gmai.com', 45.2671352, 19.8335496, 'user2', 'user2', '15320','WWW6JNQ8IR0J3422HO', 1, 1, 'user2',0,0)
INSERT INTO USER_CATEGORY_JOB (USER_ID, JOB_ID) VALUES (2,1)
INSERT INTO USER_CATEGORY_JOB (USER_ID, JOB_ID) VALUES (3,1)
INSERT INTO USER_CATEGORY_JOB (USER_ID, JOB_ID) VALUES (4,1)
INSERT INTO USER_CATEGORY_JOB (USER_ID, JOB_ID) VALUES (5,2)
INSERT INTO USER_CATEGORY_JOB (USER_ID, JOB_ID) VALUES (6,1)